# Generated by Django 5.0.3 on 2024-04-02 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='movie',
            new_name='movie_id',
        ),
    ]
